version = 1

test_patterns = ["src/**/*.test.tsx"]

[[analyzers]]
name = "javascript"
enabled = true

  [analyzers.meta]
  environment = [
    "nodejs",
    "jest"
  ]
  plugins = ["react"]
  dialect = "typescript"
  style_guide = "airbnb"
